services:
  - type: web
    name: alkf-master-land-plan
    env: python
    region: singapore
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    autoDeploy: true
